FROM microsoft/dotnet:1.1.2-sdk
WORKDIR /app

#COPY source/random-avatar /app
# copy csproj and restore as distinct layers
COPY source ./
RUN dotnet restore

# copy and build everything else
COPY . .
RUN dotnet publish -c Release -o out