FROM microsoft/dotnet:1.1.2-sdk-nanoserver
WORKDIR /app

# copy csproj and restore as distinct layers
COPY source/random-avatar /app
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out