#!/bin/bash

set -e

echo "build dotnetapp via Dockerfile.build"
docker build -t build-image -f Dockerfile.build .

echo "start build container"
docker create --name build-container build-image

echo "copy dotnetapp out of build container"
docker cp build-container:/app/source/random-avatar/out ./

echo "cleanup"
docker rm build-container 